#!/bin/bash
#
# Custom defaults on OS X Yosemite 10.10.1
# Source: https://github.com/mathiasbynens/dotfiles/blob/master/.osx
# Execute `defaults delete [domain [key]]` to revert changes

# Disable animations, e.g. opening a new window
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

# Increase window resize speed for Cocoa applications (-int 0 doesnt work)
defaults write -g NSWindowResizeTime -float 0.001

# Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Disable Mission Control animations
defaults write com.apple.dock expose-animation-duration -int 0

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -int 0

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -int 0

# Show the ~/Library folder
chflags nohidden ~/Library

# Disable send and reply animations in Mail.app (does not work in Yosemite)
#defaults write com.apple.mail DisableReplyAnimations -bool true
#defaults write com.apple.mail DisableSendAnimations -bool true

# TODO: disable full screen animation and desktop switching animation
