#!/bin/zsh
# This hook is run after every virtualenv is activated.
PROMPT='%{$fg[black]%}┌─[%{$fg[yellow]%}%~%{$fg[black]%}]$(__git_ps1 "\e[0;30m[\e[0;31m%s\e[0;30m]")%{$fg[black]%}[%{$fg[green]%}$(basename "$VIRTUAL_ENV")%{$fg[black]%}]
└─>%{$reset_color%} '
