#!/bin/zsh
# This hook is run after every virtualenv is activated.
PROMPT='%{$fg[black]%}┌─[%{$fg_bold[yellow]%}%~%{$reset_color$fg[black]%}]$(__git_ps1 "\e[0;30m[\e[1;31m%s\e[0;30m]")%{$fg[black]%}[%{$fg_bold[green]%}$(basename "$VIRTUAL_ENV")%{$reset_color$fg[black]%}]
└─╼%{$reset_color%} '

