#!/usr/bin/env bash
#
# Style gate for every script in this repo: bash, zsh, Python and Lua.
#
# Run from the repository root:
#
#   bash tests/lint_test.sh
#
# This suite breaks the rule the others keep. bootstrap_test.sh is hermetic and
# dependency-free on purpose, because a dependency to run the tests would defeat
# the point. This one shells out to shellcheck, shfmt, ruff and zsh, since a
# style gate is exactly a question about what those tools say. It reads repo
# files and writes nothing. A missing tool skips its tests with a visible
# notice rather than failing, so a half-bootstrapped machine does not report a
# failure it cannot act on.
#
# The rules themselves live beside the code they govern, not here:
# .editorconfig (layout, read natively by shfmt), .shellcheckrc (the optional
# checks that encode Google's idioms) and ruff.toml (PEP 8 selection).

# shellcheck source-path=SCRIPTDIR source=./harness.sh
source "$(dirname "${BASH_SOURCE[0]}")/harness.sh"

# icon_map.sh is vendored from kvndrsslr/sketchybar-app-font and regenerated by
# upstream's generator. Reformatting it would be reverted by the next refresh,
# and the unbraced variables are upstream's. See helpers/README.md.
#
# icon_colors.sh is this repo's own, but it is a lookup table whose case arms
# are column-aligned so a colour can be read off against its neighbours. shfmt
# strips that padding and has no option to keep it; the diff is whitespace and
# nothing else, so the alignment wins.
readonly LINT_EXCLUDE=(
  'sketchybar/.config/sketchybar/helpers/icon_map.sh'
  'sketchybar/.config/sketchybar/helpers/icon_colors.sh'
)

# Both arrays must stay non-empty. harness.sh sets `set -u`, under which
# "${ARR[@]}" on an empty array is an unbound-variable error on bash before
# 4.4. /bin/bash here is 3.2.57, which this suite is expected to run under on
# a half-bootstrapped machine.
readonly SHELLCHECK_EXCLUDE=(
  'sketchybar/.config/sketchybar/helpers/icon_map.sh'
)

# Tracked files plus untracked-but-not-ignored ones, because a script written
# here is in scope before it is ever `git add`ed, which is when a style gate is
# most useful.
repo_files() {
  git -C "${REPO_ROOT}" ls-files --cached --others --exclude-standard
}

is_excluded() {
  local needle="$1" name
  shift
  for name in "$@"; do
    [[ "${name}" == "${needle}" ]] && return 0
  done
  return 1
}

# Shebang-aware via shfmt, because sketchybarrc is a bash script with no
# extension and any *.sh glob misses it. Minus *.zsh and zsh shebangs, which
# shfmt lists but shellcheck cannot parse.
#
# Intersected with repo_files, not `git ls-files --error-unmatch`: the latter
# matches tracked paths only and would drop a brand new script, the case this
# gate most needs to cover. repo_files passes --others, so an untracked file
# that is not ignored is in scope. A scratch `try.sh` left in the repo root
# will fail the count, and that is intended rather than a bug.
# Only .gitignore'd paths are excluded.
bash_files() {
  local known file
  known="$(repo_files)"
  while read -r file; do
    # Excluded by shebang as well as by extension: shellcheck rejects a zsh
    # script outright with SC1071, and statusline.zsh shows a zsh shebang is an
    # established pattern here, so one named *.sh would fail this suite with an
    # error pointing at the wrong thing.
    [[ "${file}" == *.zsh ]] && continue
    shebang_matches "${file}" 'zsh$' && continue
    grep -Fxq "${file}" <<<"${known}" && printf '%s\n' "${file}"
  done < <(cd "${REPO_ROOT}" && shfmt -f . 2>/dev/null | sed 's|^\./||')
}

# Extension plus the rc names, which are sourced and so carry no shebang for
# shfmt to recognise.
zsh_files() {
  local file
  while read -r file; do
    case "${file}" in
      *.zsh | */.zshrc | */.zprofile | */.zshenv) printf '%s\n' "${file}" ;;
      *) is_extensionless "${file}" && shebang_matches "${file}" 'zsh$' \
        && printf '%s\n' "${file}" ;;
    esac
  done < <(repo_files)
}

# A leading dot is a prefix, not an extension: .zshrc has none.
is_extensionless() {
  local base="${1##*/}"
  [[ "${base#.}" != *.* ]]
}

# Only ever called for extensionless paths. Probing every repo file instead
# would fork twice per entry across ~90 of them, most of them binaries that
# cannot carry a shebang at all.
shebang_matches() {
  local first
  IFS= read -r first <"${REPO_ROOT}/$1" 2>/dev/null || return 1
  [[ "${first}" == '#!'* ]] || return 1
  [[ "${first}" =~ $2 ]]
}

lua_files() {
  repo_files | grep -E '\.lua$'
}

# Extension plus a shebang scan, because the glob alone misses an extensionless
# script, exactly as it does for bash.
python_files() {
  local file
  while read -r file; do
    case "${file}" in
      *.py) printf '%s\n' "${file}" ;;
      *) is_extensionless "${file}" && shebang_matches "${file}" 'python' \
        && printf '%s\n' "${file}" ;;
    esac
  done < <(repo_files)
}

# Names the module that actually declares each tool, because a SKIP line whose
# instruction does not install the tool is worse than no instruction.
have() {
  if command -v "$1" >/dev/null 2>&1; then
    return 0
  fi
  local module
  case "$1" in
    shellcheck) module='cli' ;;
    zsh) module='zsh' ;;
    *) module='neovim' ;;
  esac
  printf '  SKIP: %s is not installed. Run: bash bootstrap.sh %s\n' "$1" "${module}"
  return 1
}

setup() { :; }
teardown() { :; }

test_bash_scripts_pass_shellcheck() {
  have shellcheck || return 0

  local file output status=0
  while read -r file; do
    is_excluded "${file}" "${SHELLCHECK_EXCLUDE[@]}" && continue
    output="$(cd "${REPO_ROOT}" && shellcheck "${file}" 2>&1)" || {
      status=1
      printf '%s\n' "${output}"
    }
  done < <(bash_files)

  assert_eq 0 "${status}" 'shellcheck reports no findings'
}

test_bash_scripts_are_shfmt_clean() {
  have shfmt || return 0

  # Bare `shfmt -d`, with no formatting flags, because shfmt reads
  # .editorconfig only when none are passed. Passing -i 2 -ci -bn here would
  # test shfmt's arguments instead of the repo's checked-in style.
  local file output status=0
  while read -r file; do
    is_excluded "${file}" "${LINT_EXCLUDE[@]}" && continue
    output="$(cd "${REPO_ROOT}" && shfmt -d "${file}" 2>&1)"
    if [[ -n "${output}" ]]; then
      status=1
      printf '%s\n' "${output}"
    fi
  done < <(bash_files)

  assert_eq 0 "${status}" 'shfmt reports no reformatting'
}

# stylua is already declared in mod_neovim and driven by conform, so the repo's
# Lua was being formatted on save and checked by nothing. --config-path points
# at the repo's own copy rather than the stowed ~/.config/stylua, so the gate
# does not depend on stow having run.
test_lua_is_stylua_clean() {
  have stylua || return 0

  # lua_files, not `git ls-files`, which lists tracked paths only and would
  # skip a brand new .lua that every other gate here would catch.
  local -a files=()
  local file
  while IFS= read -r file; do
    files+=("${file}")
  done < <(lua_files)

  if ((${#files[@]} == 0)); then
    fail 'no lua files discovered'
    return 0
  fi

  local output status=0
  output="$(cd "${REPO_ROOT}" \
    && stylua --config-path stylua/.config/stylua/stylua.toml \
      --check -- "${files[@]}" 2>&1)" || status=1
  ((status == 0)) || printf '%s\n' "${output}"

  assert_eq 0 "${status}" 'stylua reports nothing to reformat'
}

# The whole zsh gate. shellcheck refuses zsh outright and shfmt's zsh dialect
# cannot parse prompt.zsh, so a parse check is all there is. See CLAUDE.md.
test_zsh_scripts_parse() {
  have zsh || return 0

  local file output status=0
  while read -r file; do
    output="$(zsh -n "${REPO_ROOT}/${file}" 2>&1)" || {
      status=1
      printf '%s: %s\n' "${file}" "${output}"
    }
  done < <(zsh_files)

  assert_eq 0 "${status}" 'every zsh file parses'
}

# Both ruff gates are handed python_files explicitly rather than letting ruff
# walk the tree, for two reasons that bare `ruff check` gets wrong:
#
#   * ruff discovers *.py only, so a `#!/usr/bin/env python3` script with no
#     extension is counted by python_files and then never linted. The count
#     would say "covered" about a file ruff never opens.
#   * `ruff format` reformats Python fences inside Markdown, which silently put
#     nine .md files, four of them vendored plugin docs, into a gate that
#     claims to cover Python. Naming the files keeps the scope honest.
#
# --no-cache because this suite is supposed to leave the repo untouched, and
# ruff otherwise writes .ruff_cache/ into it.
#
# A read loop rather than `mapfile`, which is bash 4+: /bin/bash here is 3.2.57,
# where mapfile would leave the array empty and hand ruff nothing. That passes
# both Python gates without opening a file, the silent skip this suite exists
# to prevent.
ruff_gate() {
  local -a files=()
  local file
  while IFS= read -r file; do
    files+=("${file}")
  done < <(python_files)

  # Never silently succeed on an empty list, which would be the same failure.
  if ((${#files[@]} == 0)); then
    printf 'no python files discovered\n'
    return 1
  fi

  (cd "${REPO_ROOT}" && ruff "$@" --no-cache -- "${files[@]}" 2>&1)
}

test_python_passes_ruff() {
  have ruff || return 0

  local output status=0
  output="$(ruff_gate check)" || status=1
  [[ -n "${output}" && "${status}" -ne 0 ]] && printf '%s\n' "${output}"

  assert_eq 0 "${status}" 'ruff check reports no findings'
}

test_python_is_ruff_format_clean() {
  have ruff || return 0

  local output status=0
  output="$(ruff_gate format --check)" || status=1
  [[ -n "${output}" && "${status}" -ne 0 ]] && printf '%s\n' "${output}"

  assert_eq 0 "${status}" 'ruff format reports nothing to reformat'
}

# Counts catch a script dropping out of discovery, such as a rename or a
# shebang change that makes a checked file stop being checked.
#
# They cannot catch a file that was never discovered: a count of what discovery
# found does not move when discovery misses something. That is
# test_every_extensionless_file_is_classified's job, below.
#
# Only the bash assertion needs shfmt, so the other two still run without it.
test_discovery_counts_are_stable() {
  if have shfmt; then
    assert_eq 19 "$(bash_files | wc -l | tr -d ' ')" 'bash scripts discovered'
  fi

  assert_eq 6 "$(zsh_files | wc -l | tr -d ' ')" 'zsh scripts discovered'
  assert_eq 2 "$(python_files | wc -l | tr -d ' ')" 'python scripts discovered'
  assert_eq 25 "$(lua_files | wc -l | tr -d ' ')" 'lua files discovered'
}

# Everything with a known extension is already routed: *.sh/*.bash, *.zsh and
# *.py go to their tools, and *.md/*.lua/*.toml and friends are not scripts. The
# gap is a file with no extension, where the shebang is the only signal. A file
# with neither is invisible to shfmt -f, to the *.zsh list and to ruff alike, so
# it would sit here unchecked while the suite reported success.
#
# Each such file must therefore be either discovered as a script or named below
# as deliberately not one. A new one fails until someone decides which it is.
readonly KNOWN_NON_SCRIPTS=(
  '.editorconfig'
  '.gitignore'
  '.shellcheckrc'
  'herdr/.stow-local-ignore'
  'bat/.config/bat/config'
  'fd/.config/fd/ignore'
  'ghostty/.config/ghostty/config'
  'ghostty/.config/ghostty/shaders/LICENSE'
  'git/.config/git/attributes'
  'git/.config/git/config'
  'git/.config/git/ignore'
  'ideavim/.config/ideavim/ideavimrc'
  'sketchybar/.config/sketchybar/helpers/LICENSE'
)

test_every_extensionless_file_is_classified() {
  have shfmt || return 0

  local scripts file
  scripts="$(
    bash_files
    zsh_files
    python_files
  )"

  while read -r file; do
    is_extensionless "${file}" || continue
    grep -Fxq "${file}" <<<"${scripts}" && continue
    is_excluded "${file}" "${KNOWN_NON_SCRIPTS[@]}" && continue
    fail "unclassified: ${file}. Give it a recognised extension, or add it to KNOWN_NON_SCRIPTS"
  done < <(repo_files)
}

# .editorconfig and conform.lua state the same three shfmt settings, and the
# comments in both explain why the duplication is deliberate: .editorconfig is
# what the gate reads, conform's flags are what a buffer OUTSIDE this repo gets.
# Deliberate duplication still drifts, and this repo's habit is to gate a pairing
# rather than trust it. bootstrap_test.sh exists for the same reason.
test_editorconfig_and_conform_agree_on_shfmt() {
  local ec conform
  ec="${REPO_ROOT}/.editorconfig"
  conform="${REPO_ROOT}/nvim/.config/nvim/plugin/conform.lua"

  grep -q '^indent_size = 2$' "${ec}" \
    || fail '.editorconfig does not set indent_size = 2'
  grep -q '^switch_case_indent = true$' "${ec}" \
    || fail '.editorconfig does not set switch_case_indent'
  grep -q '^binary_next_line = true$' "${ec}" \
    || fail '.editorconfig does not set binary_next_line'

  grep -q "prepend_args = { '-i', '2', '-ci', '-bn' }" "${conform}" \
    || fail 'conform.lua no longer passes -i 2 -ci -bn; .editorconfig says it should'
}

# A hand-maintained path that stops existing silently stops covering the file it
# was written for, and a rename is enough to do it.
test_listed_paths_still_exist() {
  local file
  for file in "${LINT_EXCLUDE[@]}" "${SHELLCHECK_EXCLUDE[@]}" \
    "${KNOWN_NON_SCRIPTS[@]}"; do
    [[ -f "${REPO_ROOT}/${file}" ]] || fail "listed path no longer exists: ${file}"
  done
}

# Defined in harness.sh, called here so compgen sees this suite's tests.
main "$@"
