# -*- mode: ruby -*-
# vi: set ft=ruby :

# Config variables
project_name = File.basename(Dir.pwd)
server_ip = "192.168.33.10"
server_name = server_ip + ".xip.io"
public_folder = "/vagrant"

Vagrant.configure(2) do |config|

    config.vm.box = "wong/debian-7.7.0-amd64"

    config.vm.box_url = "~/vagrant-boxes/debian-7.7.0-amd64.box"

    config.vm.network "private_network", ip: server_ip

    config.vm.define project_name do |appname|
    end

    config.vm.provider "virtualbox" do |vb|
        vb.name = project_name
        vb.cpus = 2
        vb.memory = 1024
    end

    config.vm.provision :shell, path: "install.sh",
        args: [server_name, public_folder]
end
